/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Course: typeof import('./components/Course/index.vue')['default']
    DictionaryManage: typeof import('./components/DictionaryManage/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    FamilyMember: typeof import('./components/FamilyMember/index.vue')['default']
    MainPage: typeof import('./components/MainPage/index.vue')['default']
    MenuManage: typeof import('./components/MenuManage/index.vue')['default']
    Navi: typeof import('./components/Navi/index.vue')['default']
    Password: typeof import('./components/Password/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Score: typeof import('./components/Score/index.vue')['default']
    Student: typeof import('./components/Student/index.vue')['default']
    StudentIntroduce: typeof import('./components/StudentIntroduce/index.vue')['default']
    SystemIntroduce: typeof import('./components/SystemIntroduce/index.vue')['default']
    Teacher: typeof import('./components/Teacher/index.vue')['default']
    TeacherIntroduce: typeof import('./components/TeacherIntroduce/index.vue')['default']
  }
}
